[package]
name = "Scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
env_logger = "0.11.3"
hyper = "1.3.1"
reqwest = "0.12.4"
log = "0.4.21"
thiserror = "1.0.61"
aqueiralibrary = "0.1.1"