pub enum Ports{
    FTP,
    SSH,
    Telnet,
    SMTP,
    POP3,
    IMAP,
    HTTPS,
    HTTP,
    DNS,
    DHCP,
    SNMP,
    LDAP,
    SMTPS,
    IMAPS,
    POP3S,
    MYSQL,
    RDP,
    PostgreSQL,
    Redis,
    Other,
    CPanel,
    HttpProxy,
    HostingHttp,
    WHM,
    WhmSsL,
}
pub fn ports(port: &u16) -> Ports{
    match port{
        20 | 21 => Ports::FTP,
        22 => Ports::SSH,
        23 => Ports::Telnet,
        25 => Ports::SMTP,
        53 => Ports::DNS,
        67 => Ports::DHCP,
        68 => Ports::DHCP,
        110 => Ports::POP3,
        143 => Ports::IMAP,
        161 | 162 => Ports::SNMP,
        389 => Ports::LDAP,
        443 => Ports::HTTPS,
        465 => Ports::SMTPS,
        587 => Ports::SMTP,
        993 => Ports::IMAPS,
        995 => Ports::POP3S,
        2083 => Ports::CPanel,
        2086 => Ports::WHM,
        2087 => Ports::WhmSsL,
        3306 => Ports::MYSQL,
        3389 => Ports::RDP,
        5432 => Ports::PostgreSQL,
        6379 => Ports::Redis,
        8080 => Ports::HttpProxy,
        8880 => Ports::HTTP,
        8443 => Ports::HostingHttp,
        80 => Ports::HTTP,
        _ => Ports::Other,
    }
}